This project is a Slang shader implementation of  _Ray Tracing The Next Week_. 

https://github.com/RayTracing/raytracing.github.io

== The output
image::rendered_pictures/float_depth100_sample500.bmp[Rendered image, width=800]

== Build

To use vcpkg manifest mode, remove .bak extension from vcpkg*.bak files.
[source]
----
cmake --preset ninja
cmake --build build
----

executable under build/app1

== Design Choices

It is possible to use double precision by chaning `precision_type` on "renderer_types.h" and "compute_image/rt.slang". 
Default is `float`.

Creating the hittable list is too expensive on shader; cpu creates and uploads with SSBO.
The related code is in `populateWorld()` and `createBuffers()`.

Pointer and polymorphism is limited on shader; pointer is substituted with index of SSBO.

To maintain similarity to polymorphic hittables, materials, and textures, SSBO is an array of tagged union. 
However, shader does not support `union`, so it is mimicked with Slang's reinterpret<T>.

On BVH traversal, the hit() needs access to SSBO. Rather than passing around SSBO handle, the traversal happens on only on global hit().

From Book 2 implementation, C++ code is added for CPU, because BVH construction happens on CPU side. Mostly preserves the original code.

Instead of each hittable's constructor, there is a builder for it.

Just used Vulkan for texture sampler, instead of uploading pixel SSBO to shader.

== Help

I only tested code on Linux and Nvidia GPU. I would be grateful to know errors on other platforms.

== License

This project is licensed as
https://creativecommons.org/publicdomain/zero/1.0/[CC0 1.0 Universal]
